### ISSUE TITLE
Allow passing own map

### ISSUE THREAD

**Issue by knownasilya** [cometaworks/ember-cli-google-street-view#12]
I have a map elsewhere, and I'd like to pass that same map, which could also default the lat/lng to that map's center position if they aren't supplied.

```hbs
{{street-view map=myMap}}
```

**Comment by FutoRicky** [comment]
I do not understand what you want to do. If you have a street view map already then I do not see the reason to use the component. If what you want to do is use the lat/lng of another map you already have then you would have to pass in the lat and lng in the component call because the `map` property is only a google map street view.

**Comment by miguelcobain** [comment]
I think I understand what @knownasilya is trying to do.
Basically every map instance also has an associated panorama. If you could pass in an existing map, this component could retrieve the corresponding panorama from it.
This way, all the markers from the map, for example, would be shared.

I think this is easy to implement and could lead to a superior flexibility of the component.
I can tackle this along with other minor action improvements I'm planning to PR today.
